# Generated by Django 3.1.4 on 2021-01-11 06:31

from django.db import migrations, models
import django.db.models.deletion
import job.models.helper
import job.models.helper.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='公司名称')),
                ('mobile', models.CharField(max_length=11, verbose_name='联系电话')),
                ('email', models.EmailField(max_length=128, null=True, verbose_name='邮箱')),
                ('registration_at', models.DateField(verbose_name='注册时间')),
                ('employees_num', models.PositiveIntegerField(default=0, verbose_name='员工数')),
                ('address', models.CharField(max_length=64, verbose_name='公司地址')),
                ('company_profile', models.CharField(max_length=1024, null=True, verbose_name='公司简介')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.IntegerField(verbose_name='角色名称')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('create_person', models.CharField(default='', max_length=12, verbose_name='创建人')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=11, verbose_name='姓名')),
                ('mobile', models.IntegerField(help_text='手机号不能重复', unique=True, verbose_name='手机号')),
                ('password', models.CharField(max_length=18, verbose_name='密码')),
                ('email', models.EmailField(max_length=128, null=True, verbose_name='邮箱')),
                ('role', models.ForeignKey(db_column='role_id', default=0, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='job.role', verbose_name='角色')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, job.models.helper.BaseHistoricalRecords),
        ),
        migrations.CreateModel(
            name='JianLi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='姓名')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('email', models.EmailField(max_length=128, null=True, verbose_name='邮箱')),
                ('gender', models.IntegerField(choices=[(1, '男'), (2, '女')], default=job.models.helper.enums.SexEnum['males'], verbose_name='性别')),
                ('age', models.PositiveIntegerField(default=18, verbose_name='年龄')),
                ('national', models.CharField(max_length=20, null=True, verbose_name='民族')),
                ('marriage', models.CharField(max_length=10, null=True, verbose_name='婚姻状况')),
                ('political', models.CharField(max_length=20, null=True, verbose_name='政治面貌')),
                ('education', models.CharField(max_length=20, null=True, verbose_name='学历')),
                ('graduate_school', models.CharField(max_length=20, null=True, verbose_name='毕业院校')),
                ('professional', models.CharField(max_length=20, null=True, verbose_name='专业')),
                ('work_experience', models.CharField(default='', max_length=20, verbose_name='工作经验')),
                ('live_address', models.CharField(max_length=64, verbose_name='居住地址')),
                ('work_address', models.CharField(max_length=64, null=True, verbose_name='求职地址')),
                ('native_place', models.CharField(max_length=64, null=True, verbose_name='籍贯')),
                ('job', models.CharField(max_length=20, verbose_name='岗位')),
                ('salary', models.CharField(max_length=32, verbose_name='薪水')),
                ('status', models.IntegerField(choices=[(1, '积极找工作'), (2, '即将离职')], default=job.models.helper.enums.FindJobStatusEnum['job'], verbose_name='求职状态')),
                ('work_experienced', models.CharField(max_length=256, null=True, verbose_name='工作经历')),
                ('specialty', models.CharField(max_length=256, null=True, verbose_name='特长')),
                ('is_enable', models.BooleanField(default=True, verbose_name='是否启用')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='jianli', to='job.user', verbose_name='用户')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, job.models.helper.BaseHistoricalRecords),
        ),
        migrations.CreateModel(
            name='Company2User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('status', models.BooleanField(default=True, verbose_name='状态')),
                ('company', models.ForeignKey(db_column='company_id', on_delete=django.db.models.deletion.CASCADE, related_name='company2user', to='job.company', verbose_name='公司')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='company2user', to='job.user', verbose_name='公司')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='Company', to='job.user', verbose_name='用户'),
        ),
    ]
