# Generated by Django 3.1.4 on 2021-01-12 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20210112_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(db_column='role_id', default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user', to='job.role', verbose_name='角色'),
        ),
    ]
