# Generated by Django 3.1.4 on 2021-01-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0007_add_data_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='密码'),
        ),
    ]
