# Generated by Django 3.1.5 on 2021-01-26 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0008_update_data_users_pwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLimit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_limit', to='job.user')),
            ],
            options={
                'verbose_name': '招聘用户',
                'verbose_name_plural': '招聘用户',
            },
        ),
    ]
