# Generated by Django 3.1.5 on 2021-01-26 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_userlimit'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlimit',
            name='is_enable',
            field=models.BooleanField(default=False, help_text='是否可用', verbose_name='状态'),
        ),
    ]
