# Generated by Django 3.1.5 on 2021-01-26 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0010_userlimit_is_enable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userlimit',
            name='is_enable',
            field=models.BooleanField(default=True, help_text='是否可用', verbose_name='状态'),
        ),
    ]
