# Generated by Django 3.1.5 on 2021-01-26 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0011_auto_20210126_1440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': '招聘公司'},
        ),
    ]
