# Generated by Django 3.1.5 on 2021-01-27 02:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('job', '0012_auto_20210126_1513'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCompany',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('create_at', models.DateTimeField(blank=True, editable=False, verbose_name='创建时间')),
                ('modify_at', models.DateTimeField(blank=True, editable=False, verbose_name='更新时间')),
                ('name', models.CharField(max_length=20, verbose_name='公司名称')),
                ('mobile', models.CharField(max_length=11, verbose_name='联系电话')),
                ('email', models.EmailField(max_length=128, null=True, verbose_name='邮箱')),
                ('registration_at', models.DateField(verbose_name='注册时间')),
                ('employees_num', models.PositiveIntegerField(default=0, verbose_name='员工数')),
                ('address', models.CharField(max_length=64, verbose_name='公司地址')),
                ('company_profile', models.CharField(max_length=1024, null=True, verbose_name='公司简介')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_column='user_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='job.user', verbose_name='用户')),
            ],
            options={
                'verbose_name': 'historical 招聘公司',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
