# Generated by Django 3.1.5 on 2021-01-27 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_historicalcompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalcompany',
            name='history_related_key',
            field=models.CharField(db_index=True, default='', max_length=64, verbose_name='用于关联外键的变化'),
        ),
    ]
